import type { Metadata } from "next";
import { Geist, Geist_Mono, Source_Code_Pro } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { TextMarquee } from "@/components/text-marquee";
import { ScrollRevealBg } from "@/components/layout/scroll-bg";
import { TextRevealComponent1 } from "@/components/page-components/text-reveal-1";
import localFont from "next/font/local";
import { TextRevealComponent2 } from "@/components/page-components/text-reveal-2";
import { TextRevealComponent3 } from "@/components/page-components/text-reveal-3";
import { TextRevealComponent4 } from "@/components/page-components/text-reveal-4";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const source_code = Source_Code_Pro({
    subsets: ["latin"],
    variable: "--font-source-code",
    display: "swap",
})

export const didot = localFont({
  src: "../../../public/fonts/didot_italic.otf",
  variable: "--font-didot-italic",
  display: "swap",
});

export const housing = localFont({
  src: "../../../public/fonts/housing.ttf",
  variable: "--font-housing",
  display: "swap",
});

export const magnat_text_regular = localFont({
  src: "../../../public/fonts/magnat_family/text_test/magnat_text_test_regular.woff",
  variable: "--font-magnat_text_regular",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `  ${geistSans.variable}
              ${geistMono.variable}
              ${source_code.variable}
              ${didot.variable}
              ${housing.variable}
              ${magnat_text_regular.variable} antialiased`,
          "bg-[#DF4346] overflow-x-hidden",
        )}
      >
        <ScrollRevealBg />
        <TextMarquee />
        <main>{children}</main>
        <TextRevealComponent1/>
        <TextRevealComponent2/>
        <TextRevealComponent3/>
        <TextRevealComponent4/>
      </body>
    </html>
  );
}
